# Theme Settings Configuration File
##
### use settings.yml file for configure colors, ui, rtl, sidebar, animation options

### Main Settings
settings:
  skin: "light" # select initial skin option: "light" or "dark"

### Preloader
preloader:
  logo:
    image: "assets/img/logo2.png"
    alt: ""

### Header
header:
  logo:
    image: "assets/img/logo2.png"
    alt: "JH"

### Social
social:
  - title: "Github"
    icon: "fab fa-github"
    url: "http://github.com/jamesdin32/"

  - title: "LinkedIn"
    icon: "fab fa-linkedin-in"
    url: "https://www.linkedin.com/in/jeanhyok-bang-61b701369/"

  # - title: "Behance"
  #   icon: "fab fa-behance"
  #   url: "http://behance.com"

### Footer
footer:
  developer: "Powered by <strong>JH</strong>"

### Portfolio Filters Settings
portfolio:
  layout: "list" # select works layout options: "Grid" or "List"
  filters:
    - name: "Certification"
      slug: "Cert"

    - name: "Academic Background"
      slug: "Achieve"

    - name: "PROJECT"
      slug: "PROJECT"

    # - name: "Branding"
    #   slug: "branding"
